server:
  applicationConnectors:
  - type: http
    port: 8080
  adminConnectors:
  - type: http
    port: 8081
  rootPath: /webprotege-rest-api/*
dataPath: "H:/Projekte/Leipzig Health Atlas/Development/Web-Service/data/webprotege/"