server:
  applicationConnectors:
  - type: http
    port: 8080
  rootPath: /ontology-service/*
  adminConnectors:
  - type: http
    port: 8081
  adminContextPath: /ontology-service
  requestLog:
    appenders: []
logging:
  level: WARN
dataPath: srv/data/webprotege/
webprotegeRelativeToWebroot: /webprotege
rootPath: /ontology-service
phenotypePath: srv/data/ontology-service/cop_%id%.owl
mongoHost: localhost
mongoPort: 27017
