server:
  applicationConnectors:
  - type: http
    port: 8080
  rootPath: /ontology-service/*
  adminConnectors:
  - type: http
    port: 8081
  adminContextPath: /ontology-service
dataPath: "src/test/resources/data/webprotege/"
webprotegeRelativeToWebroot: /webprotege
rootPath: /ontology-service