server:
  applicationConnectors:
  - type: http
    port: 8080
  adminConnectors:
  - type: http
    port: 8081
  rootPath: /webprotege-rest-api/*
dataPath: "/data/webprotege/"
webprotegeRelativeToWebroot: /webprotege
rootPath: /webprotege-rest-api/
