server:
  applicationConnectors:
  - type: http
    port: 8080
  rootPath: /ontology-service/*
  adminConnectors:
  - type: http
    port: 8081
  adminContextPath: /ontology-service
  requestLog:
    appenders: []
  registerDefaultExceptionMappers: false
  detailedJsonProcessingExceptionMapper: true
logging:
  level: WARN
dataPath: /srv/webprotege/
webprotegeRelativeToWebroot: /webprotege
rootPath: /ontology-service
phenotypePath: /data/ontology-service/cop_%id%.owl
mongoHost: mongodb
mongoPort: 27017
