server:
  applicationConnectors:
  - type: http
    port: 8080
  adminConnectors:
  - type: http
    port: 8081
  rootPath: "/app/*"
dataPath: "H:/Projekte/Leipzig Health Atlas/Development/Web-Service/data/webprotege/"
