server:
  applicationConnectors:
  - type: http
    port: 8080
  rootPath: /ontology-service/*
  adminConnectors:
  - type: http
    port: 8081
  adminContextPath: /ontology-service
  requestLog:
    appenders: []
dataPath: H:/Projekte/Leipzig Health Atlas/Development/Web-Service/data/webprotege/
webprotegeRelativeToWebroot: /webprotege
rootPath: /ontology-service
phenotypePath: H:/Projekte/Leipzig Health Atlas/Development/Web-Service/data/ontology-service/cop_%id%.owl
