server:
  applicationConnectors:
  - type: http
    port: 8080
  rootPath: /ontology-service/*
  adminConnectors:
  - type: http
    port: 8081
  adminContextPath: /ontology-service
  requestLog:
    appenders: []
dataPath: /data/webprotege/
webprotegeRelativeToWebroot: /webprotege
rootPath: /ontology-service
phenotypePath: /data/ontology-service/cop_%id%.owl
